# Generated by Django 4.0.3 on 2022-03-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_deal_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='wage',
            field=models.IntegerField(null=True),
        ),
    ]
