# Generated by Django 4.0.3 on 2022-03-18 14:48

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_remove_deal_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
